### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by Sandmania** [edwardcapriolo/farsandra#21]
Farsandra assumes that Cassandra ships with log4j-server.properties. This file does not exist in cassandra 2.1.x or 2.2.x

**Comment by jancona** [comment]
I tried ignoring the failure to find log4j-server.properties, but it failed later with:
```
java.lang.RuntimeException: looking to make 1 replacement but made 0 . Likely that farsandra does not understand this version of configuration file. 
	at io.teknek.farsandra.Farsandra.replaceThisWithThatExpectNMatch(Farsandra.java:523)
	at io.teknek.farsandra.Farsandra.start(Farsandra.java:322)
```
So I'm guessing that there are other config file changes that have to be accounted for.

Any plans to upgrade Farsandra to support versions beyond 2.0?

**Comment by edwardcapriolo** [comment]
Up until this point the logic did not have to be versioned to change things. We probably have to do that. I will look at the 3.0 config

**Comment by edwardcapriolo** [comment]
Should we consider this closed now?
